[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  domain = "app-demo.fairmind.xyz"

[context.deploy-preview]
  domain = "app-demo-preview.fairmind.xyz"
