headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "/Users/adhi/Desktop/Documents/learn/fairmind-ethical-sandbox/fairmind-website/functions"
functionsDirectoryOrigin = "config"

[functions]

[functions."*"]

[build]
publish = "/Users/adhi/Desktop/Documents/learn/fairmind-ethical-sandbox/fairmind-website/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/adhi/Desktop/Documents/learn/fairmind-ethical-sandbox/fairmind-website"
command = "bun run build"
functions = "/Users/adhi/Desktop/Documents/learn/fairmind-ethical-sandbox/fairmind-website/functions"

[build.environment]
NODE_VERSION = "18"
NODE_ENV = "production"
SITE_URL = "https://fairmind.xyz"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://www.googletagmanager.com https://static.hotjar.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://unpkg.com https://www.google-analytics.com; frame-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/docs"
to = "/docs/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog"
to = "/blog/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]