'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { IconFileAnalytics, IconLoader2, IconRefresh } from '@tabler/icons-react'

import { Button } from '@/components/ui/button'
import { apiClient } from '@/lib/api/api-client'
import { API_ENDPOINTS } from '@/lib/api/endpoints'
import { ReportHistoryTable, type SavedReport } from '../../audit-reports/components/ReportHistoryTable'
import { ReportPreview } from '../../audit-reports/components/ReportPreview'

type ReportSystem = {
  id: string
  name: string
  owner: string
  riskTier: string
  lifecycleStage: string
  readiness: number
}

export type AssurancePdfContext = {
  frameworkLabel: string
  assuranceAsOf?: string
  readiness: {
    applicable: number
    accepted: number
    blockingFindings: number
    missingEvidence: number
    staleEvidence: number
  } | null
  evidenceRuns: Array<{
    sourceIdentifier: string
    suiteName: string | null
    contentHash: string
    result: string
    capturedAt: string | null
  }>
  controls: Array<{
    externalId: string
    title: string
    openFindings: number | null
  }>
  limitations: string[]
}

type PdfRecord = Record<string, unknown>

function records(value: unknown): PdfRecord[] {
  return Array.isArray(value)
    ? value.filter((item): item is PdfRecord => Boolean(item) && typeof item === 'object')
    : []
}

function textValue(record: PdfRecord, keys: string[], fallback = 'Not recorded') {
  for (const key of keys) {
    const value = record[key]
    if (typeof value === 'string' && value.trim()) return value
    if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  }
  return fallback
}

export function buildAssurancePdfLines(report: SavedReport, context: AssurancePdfContext): string[] {
  const system = (report.data.system || {}) as PdfRecord
  const risks = records(report.data.risks)
  const remediations = records(report.data.remediation ?? report.data.remediations)
  const decisions = records(report.data.approvals ?? report.data.decisions)
  const unresolvedControls = context.controls.filter((control) => (control.openFindings ?? 0) > 0)
  const unknownFindingCounts = context.controls.filter((control) => control.openFindings == null).length
  const frameworkScope = context.frameworkLabel || report.config.frameworks?.join(', ') || 'Not recorded'
  const lines = [
    context.assuranceAsOf ? 'Current Assurance Package' : report.title,
    `Assurance data as of: ${context.assuranceAsOf || report.createdAt || 'Not recorded'}`,
    `Operational source snapshot: ${report.title} generated ${report.createdAt || 'Not recorded'}`,
    `Source report ID: ${report.id}`,
    `Source report generated by: ${report.generatedBy || 'Not recorded'}`,
    '',
    '## Scope and version',
    `System: ${textValue(system, ['name'], report.systemId)}`,
    `System ID: ${report.systemId}`,
    `Owner: ${textValue(system, ['owner'])}`,
    `Framework scope: ${frameworkScope}`,
    '',
    '## Readiness and rejected assessments',
  ]

  if (context.readiness) {
    lines.push(
      `Accepted controls: ${context.readiness.accepted} / ${context.readiness.applicable}`,
      `Rejected assessments: ${context.readiness.blockingFindings}`,
      `Controls missing accepted evidence: ${context.readiness.missingEvidence}`,
      `Controls with stale evidence: ${context.readiness.staleEvidence}`,
    )
  } else {
    lines.push('Readiness: Not available for this report scope')
  }

  lines.push('', '## Evidence index')
  if (context.evidenceRuns.length === 0) {
    lines.push('No evidence runs are recorded for this report scope.')
  } else {
    context.evidenceRuns.forEach((run, index) => {
      lines.push(
        `${index + 1}. ${run.suiteName || run.sourceIdentifier} | result: ${run.result || 'not recorded'} | captured: ${run.capturedAt || 'not recorded'}`,
        `   Source: ${run.sourceIdentifier} | SHA-256: ${run.contentHash}`,
      )
    })
  }

  lines.push('', '## Risks and unresolved findings')
  const knownOpenFindings = unresolvedControls.reduce((sum, control) => sum + (control.openFindings ?? 0), 0)
  lines.push(unknownFindingCounts > 0
    ? `Open control findings: ${knownOpenFindings} known; ${unknownFindingCounts} control counts not available`
    : `Open control findings: ${knownOpenFindings}`)
  unresolvedControls.forEach((control) => {
    lines.push(`- ${control.externalId} ${control.title}: ${control.openFindings} open`)
  })
  if (risks.length === 0) {
    lines.push('No report-level risks were recorded in this snapshot.')
  } else {
    risks.forEach((risk) => {
      lines.push(`- ${textValue(risk, ['title', 'name', 'id'])} | severity: ${textValue(risk, ['severity'])} | status: ${textValue(risk, ['status'])}`)
    })
  }

  lines.push('', '## Remediation')
  if (remediations.length === 0) {
    lines.push('No remediation items were recorded in this snapshot.')
  } else {
    remediations.forEach((item) => {
      lines.push(`- ${textValue(item, ['title', 'name', 'description', 'id'])} | status: ${textValue(item, ['status'])} | owner: ${textValue(item, ['owner', 'assignedTo'])}`)
    })
  }

  lines.push('', '## Approval records and decisions')
  if (decisions.length === 0) {
    lines.push('No approval or assurance decisions were recorded in this snapshot.')
  } else {
    decisions.forEach((decision) => {
      lines.push(
        `- ${textValue(decision, ['status', 'decision'])} | requested by ${textValue(decision, ['requestedBy', 'decidedBy', 'reviewedBy', 'actor'])}`,
        `  Decision notes: ${textValue(decision, ['decisionNotes', 'notes', 'rationale', 'reason'])}`,
      )
    })
  }

  lines.push('', '## Limitations')
  if (context.limitations.length === 0) {
    lines.push('No evaluation limitations were recorded; absence of a recorded limitation is not evidence that none exist.')
  } else {
    context.limitations.forEach((limitation) => lines.push(`- ${limitation}`))
  }
  lines.push('', 'This operational snapshot supports readiness review and does not constitute certification or an assurance opinion.')
  return lines
}

function downloadJson(report: SavedReport) {
  const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${report.title.replace(/\s+/g, '_')}.json`
  anchor.click()
  URL.revokeObjectURL(url)
}

async function downloadPdf(report: SavedReport, context: AssurancePdfContext) {
  const { jsPDF } = await import('jspdf')
  const document = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = document.internal.pageSize.getWidth()
  const pageHeight = document.internal.pageSize.getHeight()
  const margin = 40
  const contentWidth = pageWidth - margin * 2
  let y = margin

  const currentContext = { ...context, assuranceAsOf: new Date().toISOString() }
  for (const rawLine of buildAssurancePdfLines(report, currentContext)) {
    if (!rawLine) {
      y += 6
      continue
    }
    const heading = rawLine.startsWith('## ')
    const line = heading ? rawLine.slice(3) : rawLine
    document.setFont('helvetica', heading || y === margin ? 'bold' : 'normal')
    document.setFontSize(heading ? 13 : y === margin ? 18 : 9)
    const wrapped = document.splitTextToSize(line, contentWidth) as string[]
    const lineHeight = heading ? 16 : 12
    if (y + wrapped.length * lineHeight > pageHeight - margin) {
      document.addPage()
      y = margin
    }
    document.text(wrapped, margin, y)
    y += wrapped.length * lineHeight + (heading ? 4 : 0)
  }
  const systemName = textValue((report.data.system || {}) as PdfRecord, ['name'], report.systemId)
  document.save(`Current_Assurance_${systemName.replace(/\s+/g, '_')}.pdf`)
}

export function reportMatchesAssuranceScope(report: SavedReport, systemId: string, frameworkLabel: string) {
  const frameworks = report.config.frameworks || []
  return report.systemId === systemId
    && frameworks.length === 1
    && frameworks[0] === frameworkLabel
}

export function AssuranceReportStudio({
  system,
  frameworkLabel,
  assurance,
  readOnly,
}: {
  system: ReportSystem
  frameworkLabel: string
  assurance: AssurancePdfContext
  readOnly: boolean
}) {
  const scopeKey = `${system.id}:${frameworkLabel}`
  const scopeKeyRef = useRef(scopeKey)
  scopeKeyRef.current = scopeKey
  const historyRequestIdRef = useRef(0)
  const generationRequestIdRef = useRef(0)
  const [historySnapshot, setHistorySnapshot] = useState<{
    scopeKey: string
    reports: SavedReport[]
    loading: boolean
    error: string | null
  }>({ scopeKey, reports: [], loading: true, error: null })
  const [generationSnapshot, setGenerationSnapshot] = useState({ scopeKey, loading: false })
  const [previewSnapshot, setPreviewSnapshot] = useState<{ scopeKey: string; report: SavedReport } | null>(null)
  const history = historySnapshot.scopeKey === scopeKey ? historySnapshot.reports : []
  const historyLoading = historySnapshot.scopeKey !== scopeKey || historySnapshot.loading
  const error = historySnapshot.scopeKey === scopeKey ? historySnapshot.error : null
  const generating = generationSnapshot.scopeKey === scopeKey && generationSnapshot.loading
  const preview = previewSnapshot?.scopeKey === scopeKey ? previewSnapshot.report : null

  const reportMatchesScope = useCallback((report: SavedReport) => {
    return reportMatchesAssuranceScope(report, system.id, frameworkLabel)
  }, [frameworkLabel, system.id])

  const loadHistory = useCallback(async () => {
    const targetScope = scopeKey
    const requestId = ++historyRequestIdRef.current
    setHistorySnapshot({ scopeKey: targetScope, reports: [], loading: true, error: null })
    try {
      const response = await apiClient.get<SavedReport[]>(
        `${API_ENDPOINTS.aiGovernance.listReports}?system_id=${encodeURIComponent(system.id)}`,
      )
      if (!response.success) throw new Error(response.error || 'Saved report history is unavailable')
      if (requestId === historyRequestIdRef.current && scopeKeyRef.current === targetScope) {
        setHistorySnapshot({
          scopeKey: targetScope,
          reports: (response.data || []).filter(reportMatchesScope),
          loading: false,
          error: null,
        })
      }
    } catch (reason) {
      if (requestId === historyRequestIdRef.current && scopeKeyRef.current === targetScope) {
        setHistorySnapshot({
          scopeKey: targetScope,
          reports: [],
          loading: false,
          error: reason instanceof Error ? reason.message : 'Saved report history is unavailable',
        })
      }
    }
  }, [reportMatchesScope, scopeKey, system.id])

  useEffect(() => {
    setPreviewSnapshot(null)
    void loadHistory()
  }, [loadHistory])

  const generate = async () => {
    const targetScope = scopeKey
    const requestId = ++generationRequestIdRef.current
    setGenerationSnapshot({ scopeKey: targetScope, loading: true })
    try {
      const response = await apiClient.post<SavedReport>(API_ENDPOINTS.aiGovernance.generateReport, {
        system_id: system.id,
        report_type: 'governance',
        title: 'Governance Assurance Summary',
        frameworks: [frameworkLabel],
        sections: ['executive_summary', 'risk_overview', 'evidence_summary', 'remediations', 'decision_log'],
      })
      if (!response.success || !response.data) throw new Error(response.error || 'Report generation failed')
      if (requestId === generationRequestIdRef.current && scopeKeyRef.current === targetScope) {
        const generated = response.data
        setPreviewSnapshot({ scopeKey: targetScope, report: generated })
        setHistorySnapshot((current) => current.scopeKey === targetScope
          ? {
              ...current,
              reports: [generated, ...current.reports.filter((report) => report.id !== generated.id)],
              error: null,
            }
          : current)
      }
    } catch (reason) {
      if (requestId === generationRequestIdRef.current && scopeKeyRef.current === targetScope) {
        setHistorySnapshot((current) => current.scopeKey === targetScope
          ? { ...current, error: reason instanceof Error ? reason.message : 'Report generation failed' }
          : current)
      }
    } finally {
      if (requestId === generationRequestIdRef.current && scopeKeyRef.current === targetScope) {
        setGenerationSnapshot({ scopeKey: targetScope, loading: false })
      }
    }
  }

  return (
    <section aria-label="Report builder and history" className="border-4 border-[#0F1412] bg-[#FCFDF8] shadow-[8px_8px_0_0_#0F1412]">
      <div className="flex flex-col gap-3 border-b-4 border-[#0F1412] bg-[#F3F5F0] p-5 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-xs font-black uppercase tracking-[0.16em] text-[#0B7659]">Saved operational reports</p>
          <h2 className="mt-1 text-xl font-black uppercase">Assurance Report Studio</h2>
          <p className="mt-1 max-w-[70ch] text-sm text-[#59615D]">Generate, preview, export, and revisit operational report snapshots for {system.name}. Framework assurance remains governed by the transparent summary above.</p>
        </div>
        <Button type="button" variant="neutral" disabled={historyLoading} onClick={() => void loadHistory()} className="rounded-none border-2 border-[#0F1412] bg-[#FCFDF8] font-black uppercase">
          <IconRefresh aria-hidden="true" /> Refresh history
        </Button>
      </div>

      {error ? <p role="alert" className="m-5 border-2 border-[#D83A2E] bg-[#FFF0ED] p-3 text-sm font-bold">{error}</p> : null}

      {!readOnly ? (
        <div className="grid gap-4 border-b-2 border-[#0F1412] p-5 lg:grid-cols-[1fr_auto] lg:items-end">
          <div>
            <p className="text-xs font-black uppercase text-[#59615D]">Pinned generator scope</p>
            <p className="mt-1 font-black">{system.name} · {frameworkLabel}</p>
            <p className="mt-1 text-sm text-[#59615D]">The generated legacy operational snapshot is stored in report history. It does not replace the evidence-hash assurance summary.</p>
          </div>
          <Button type="button" disabled={generating} onClick={() => void generate()} className="rounded-none border-2 border-[#0F1412] bg-[#E97522] font-black uppercase text-[#0F1412]">
            {generating ? <IconLoader2 aria-hidden="true" className="animate-spin" /> : <IconFileAnalytics aria-hidden="true" />}
            {generating ? 'Generating report' : 'Generate report'}
          </Button>
        </div>
      ) : (
        <p className="border-b-2 border-[#0F1412] bg-[#E5F4EF] p-4 text-sm font-bold">Auditor mode can preview and export saved reports but cannot generate a new snapshot.</p>
      )}

      {preview ? (
        <div className="border-b-2 border-[#0F1412] p-5">
          <p className="mb-3 text-xs font-black uppercase tracking-[0.12em] text-[#59615D]">Selected preview · {preview.title}</p>
          <ReportPreview
            reportType={preview.reportType}
            system={preview.data.system}
            data={preview.data}
            sections={preview.config.sections || []}
            frameworks={preview.config.frameworks || []}
          />
        </div>
      ) : null}

      <div className="p-5">
        <h3 className="mb-3 font-black uppercase">Saved Report History</h3>
        <ReportHistoryTable
          reports={history}
          loading={historyLoading}
          onPreview={(report) => setPreviewSnapshot({ scopeKey, report })}
          onDownloadJson={downloadJson}
          onDownloadPdf={(report) => void downloadPdf(report, assurance)}
        />
      </div>
    </section>
  )
}
