[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NETLIFY_IMAGES_CDN_DOMAIN = "fairmind.xyz"

# Form handling configuration
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.netlify.com https://www.google-analytics.com; form-action 'self' https://api.netlify.com;"

# Form submission notifications
[[redirects]]
  from = "/contact-success"
  to = "/contact?success=true"
  status = 200

[[redirects]]
  from = "/contact-error"
  to = "/contact?error=true"
  status = 200

[dev]
  command = "bun run dev"
  port = 4321
  publish = "dist"
